send stamp every 2sec
KoukiNAGATA/sushi-chat pull request #159
Opened 2021-05-08 18:43 UTC by Eri-0910

Roomの中に実装し直した

Topicのなんかやったときに、
activeなトピックがある　かつ　タイマーがない　ならタイマーセット
activeなトピックがない　かつ　タイマーがある　ならタイマークリア

2021-05-08 18:52 UTC, yuta-ike requested changes

2021-05-08 18:52 UTC, yuta-ike commented on server/src/models/room.ts
> +        RoomClass.globalSocket.to(this.id),
これ確かアンチパターンです。 `.to(...).emit(..)`は分解せずに同期的に実行しないといけない

https://socket.io/docs/v4/rooms/ の Usage with asynchronous code

2021-05-08 18:52 UTC, yuta-ike commented on server/src/models/room.ts
> +        RoomClass.globalSocket.to(this.id),
globalSocketごと渡した方が良さそうです

2021-05-08 18:54 UTC, yuta-ike commented
> activeなトピックがある　かつ　タイマーがない　ならタイマーセット
activeなトピックがない　かつ　タイマーがある　ならタイマークリア

ルームの開始と終了でセットとクリアをした方が簡潔っぽいです！開始は`startRoom`、終了は`finishRoom`ですー

2021-05-08 18:55 UTC, Eri-0910 commented
> > activeなトピックがある　かつ　タイマーがない　ならタイマーセット
> > activeなトピックがない　かつ　タイマーがある　ならタイマークリア
> 
> ルームの開始と終了でセットとクリアをした方が簡潔っぽいです！開始は`startRoom`、終了は`finishRoom`ですー

これ、閉め忘れを考えてわざとトピックにしたんやけど、どう思う？

2021-05-08 18:56 UTC, yuta-ike commented
あーなるほど

2021-05-08 18:56 UTC, yuta-ike commented
確かにそれなら良さそうです！

2021-05-09 00:20 UTC, yuta-ike commented
LGTMだけどVercelがコケてるな

2021-05-09 00:49 UTC, yuta-ike approved these changes
LGTM

2021-05-09 00:49 UTC, merged