Nagata/front/vuex topic2
KoukiNAGATA/sushi-chat pull request #304
Opened 2021-08-14 12:09 UTC by KoukiNAGATA

close #207

## やったこと
- topic
- topicState
のvuex

## 参考リンク・補足など

2021-08-14 12:45 UTC, KoukiNAGATA commented
一般ユーザーでstateが反映されてない
一旦draft

2021-08-14 13:17 UTC, KoukiNAGATA commented
状態を反映done

2021-08-15 05:09 UTC, knknk98 commented on app/front/pages/index.vue
> +          :topic-state="topicStateItems[chatData.topic.id]"
vuex導入してるんだからpropsで渡す必要ないのでは

2021-08-18 15:21 UTC, knknk98 reviewed
TopicHeaderのpropsもtopicStateいらないのでは

2021-08-18 15:24 UTC, KoukiNAGATA commented
> TopicHeaderのpropsもtopicStateいらないのでは

chatDataのをvuexで渡せればいらなくなるなぁ

2021-08-19 16:08 UTC, knknk98 requested changes
<img width="462" alt="スクリーンショット 2021-08-20 1 06 26" src="https://user-images.githubusercontent.com/65712721/130103505-28f9f9cf-5c70-49a4-8e04-9e1027a67035.png">
デプロイ先のやつでルームをオープンする押してもこうなっちゃった

2021-08-19 17:30 UTC, KoukiNAGATA commented
未開始時にコメントできて開始したらできなくなってた
直します

2021-08-19 17:41 UTC, knknk98 approved these changes

2021-08-19 17:42 UTC, merged