[WIP]get /room/:id の作成
KoukiNAGATA/sushi-chat pull request #386
Opened 2021-09-19 02:13 UTC by Eri-0910

close #xxx

## やったこと
get /room/:id できるようにした

## 困っていること

adminなら`adminInviteKey`を返す必要がある。逆にそうでなければ返してはいけない。
（ヘッダーにadminの情報が載っていたというのは前提として、)このルームの管理者かどうかをどう確認すべきか迷っている。

今は `RoomService` にあるルームの adminかどうかを確認しbooleanを返す関数 `isAdmin` を作っていて、`rest.ts` の方で`isAdmin`の結果をもとに`room`の何の情報を返すかを決めようとしています

`rest.ts` にどれくらい操作させていいのかなーとか考えつつ、他の実装方針で考えたのは以下の通りなのですが、ご意見をお聞けせ願えればと。

1：`RoomService` にadminかどうかで返すroomの形が変わるような`find`を作る
`rest.ts` で返すオブジェクト作るときに結局admin判別が必要で、`adminInviteKey`を含んでいるかどうかで判断するか、roomに加えadminかどうかも`RoomService` から返すということを考え、どっちも微妙かなぁと思った。

2：`isAdmin`を`RoomService`に作るのではなく`AdminService`みたいなのを増やして作る
自分が管理しているルームの一覧を取得する `get /room` も作らないといけないので、adminという概念が必要なのではないか。という発想。

## 参考リンク・補足など

2021-09-20 12:14 UTC, TOMOFUMI-KONDO requested changes

2021-09-20 12:14 UTC, TOMOFUMI-KONDO commented on app/server/src/rest.ts
> +      })
`find`というメソッドを`/room/:id/history`のエンドポイントと`/room/:id`のエンドポイントで使い回していますが、これらは別のユースケースなのでそれぞれのメソッドを用意すべきだと思います。
実際、`/room/:id`のエンドポイントではRestRoomService`から二つのメソッドを呼び出す不思議な形になっているので、これらを一つのユースケースとしてそれ用のメソッドを用意すべきだと思います

2021-09-20 12:29 UTC, Eri-0910 commented on app/server/src/rest.ts
> +      })
あー、そうですね。

最初adminInviteKeyがnullableと気が付かず、admin稼働かで帰ってくるオブジェクトの方から違うの気持ち悪いなと思ってわざと2つのメソッドに分けたんですけど、nullableなのでそんな気にしなくていいですね。

修正します。

2021-09-20 13:43 UTC, Eri-0910 commented on app/server/src/rest.ts
> +      })
池奥先生の便利shared使って型つけました。topicsが型合わないので空の配列にしていたり、nameだったり、stateも修正前のコードっぽいので適当にOPEN入れてます。この辺は全部合わせてどこかで修正したい。

2021-09-20 14:09 UTC, yuta-ike commented on app/server/src/rest.ts
> +      })
わお、その辺忘れてた。
今影響範囲少ない（というか多分ここしかない）ので一緒に修正してもらっても大丈夫です（面倒でしたら私の方で修正反映しますー）

2021-09-20 14:32 UTC, Eri-0910 commented on app/server/src/rest.ts
> +      })
topicはこっちの問題で合わないのですが、それ以外は修正しました！

2021-09-20 14:51 UTC, TOMOFUMI-KONDO approved these changes
コメントしましたが、動作はしそうなので後好きにマージしちゃって大丈夫です〜

2021-09-20 14:51 UTC, TOMOFUMI-KONDO commented on app/server/src/rest.ts
> +      const room = await roomService.checkAdminAndfind({
名前が微妙な気がしますが、動作は変わらないのでとりあえずこのままでも問題ないです

Ref:https://qiita.com/takasek/items/693c57dc9ddc6c1eb1ba#%E3%83%AA%E3%83%95%E3%82%A1%E3%82%AF%E3%82%BF%E3%83%AA%E3%83%B3%E3%82%B0%E3%82%88%E3%82%8A

2021-09-20 14:51 UTC, TOMOFUMI-KONDO commented on app/server/src/service/room/RestRoomService.ts
> +    }
adminInviteKey以外は重複しているので1箇所にまとめた方が変更の際に嬉しいと思います！

2021-09-20 14:59 UTC, Eri-0910 commented on app/server/src/rest.ts
> +      const room = await roomService.checkAdminAndfind({
悩んで諦めた結果のネーミングなんですけど、何が適切だと思います……？

2021-09-21 02:53 UTC, Eri-0910 commented
ネーミングは一旦諦め！
オブジェクトはまとめました〜

2021-09-21 02:55 UTC, merged