[WIP]ルームの開始
KoukiNAGATA/sushi-chat pull request #389
Opened 2021-09-19 05:48 UTC by Eri-0910

close #xxx

## やったこと

`PUT /room/:id/start` を作った
そのルームのadminなら開始できるようにした
socket.io側からこれ関連の処理を消した
RoomのjoinUserで、ルーム開始前はエラーを返すようにした
socket.ioのアプリケーションサービスの方で、`ADMIN_ENTER_ROOM`と`ENTER_ROOM`の中の処理の順番を変えて、Userにroom情報記憶させる前にroomにuser参加させることでroomの開始を確認できるようにした

## 動作確認手順

検討中……

## 困っていること

User側のenterRoomでもroomの開始チェックしなくていいのだろうか(こんな微妙な実行順依存いいのか？でもチェックできない……？)

## 参考リンク・補足など

2021-09-19 14:59 UTC, Eri-0910 commented
話してたのは多分直した。

コンフリクトは明日。

2021-09-20 12:35 UTC, yuta-ike commented on app/server/src/service/user/UserService.ts
> +    const user = this.userRepository.find(command.userId)
`userRepository.find`の返り値の型が間違っていて、本来は`User | null`なのでnullチェックが必要だった気がする cc @TOMOFUMI-KONDO

2021-09-20 12:35 UTC, yuta-ike commented on app/server/src/service/user/UserService.ts
> +    const user = this.userRepository.find(command.userId)
`userRepository.find`の返り値の型が間違っていて、本来は`User | null`なのでnullチェックが必要だった気がする cc @TOMOFUMI-KONDO

2021-09-20 12:59 UTC, TOMOFUMI-KONDO requested changes

2021-09-20 12:59 UTC, TOMOFUMI-KONDO commented on app/server/src/domain/user/User.ts
> +  private _isAdmin = false
二点コメントで、
1. getterメソッドを作らないなら`_`のprefixはなくても大丈夫
2. isAdminはAdminのコネクション時に決まるので、idと同様にconstructorから注入できるようにしたい

2021-09-20 12:59 UTC, TOMOFUMI-KONDO commented on app/server/src/service/user/UserService.ts
> +    const user = this.userRepository.find(command.userId)
あ、そうです！正しくはこうなります
```
interface IUserRepository {
  create(user: User): void
  update(user: User): void
  find(userId: string): Promise<User | null>
  selectByRoomId(roomId: string): Promise<User[]>
}
```

俺の方で直しておくのでこのままにしてもいいですよ

2021-09-20 13:06 UTC, Eri-0910 commented on app/server/src/service/user/UserService.ts
> +    const user = this.userRepository.find(command.userId)
これ直すと他にも飛び火した挙句修正もらしそうなので、お任せすることにします

2021-09-20 14:24 UTC, Eri-0910 commented
CreateUser を ENTER_ROOM系の中に入れた。テストしようと思ったけど、テストのしようがない……

2021-09-20 14:35 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +  private _isAdmin = false
create userを移す方向で変更DONEです

2021-09-20 14:37 UTC, yuta-ike commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean | null,
_isAdminがnullになるケースなさそう？（iconIdとroomIdもか）

2021-09-20 14:37 UTC, yuta-ike commented on app/server/src/service/user/UserService.ts
> +    // roomにjoinできたらuserも作成
感覚的にuserの作成の後にjoinな気がしましたがトランザクション的処理なのでどっちでも良さそう。

2021-09-20 14:44 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean | null,
leaveroomがあるんです

2021-09-20 14:46 UTC, Eri-0910 commented on app/server/src/service/user/UserService.ts
> +    // roomにjoinできたらuserも作成
ちょっと悩んだ……

assertルーム開始済み
assertアドミン
ユーザー作成
ルームにジョイン

みたいにした方がいいのかな(今は1,2,4が一つになってるイメージ)

2021-09-20 14:59 UTC, TOMOFUMI-KONDO requested changes

2021-09-20 14:59 UTC, TOMOFUMI-KONDO commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean | null,
`roomId`,`iconId`,`isAdmin`にに`null`が入ることははなさそう？
なので全部`public readonly`にしてgetterとgetXXXOrThrowみたいなのもいらないかも

2021-09-20 14:59 UTC, TOMOFUMI-KONDO commented on app/server/src/domain/user/User.ts
> +  private assertHasIsAdmin(
`isAdmin === true`のチェックも必要？

2021-09-20 14:59 UTC, TOMOFUMI-KONDO commented on app/server/src/service/user/UserService.ts
>      this.userRepository.update(user)
updateはいらなそう

2021-09-20 14:59 UTC, TOMOFUMI-KONDO commented on app/server/src/service/user/UserService.ts
>      this.userRepository.update(user)
update はいらなそう

2021-09-20 14:59 UTC, yuta-ike commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean | null,
なるほど.................
enterRoomでユーザー作成なら、leaveRoomでユーザー破棄しないとデータが残り続けてしまうからそっちの処理が必要になる？ cc @TOMOFUMI-KONDO

2021-09-20 15:00 UTC, Eri-0910 commented on app/server/src/service/user/UserService.ts
>      this.userRepository.update(user)
あー、消し損ねてますね

2021-09-20 15:02 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +  private assertHasIsAdmin(
あ、なるほど。
上に合わせてisAdminの情報を持っているということを保証したけど、assertIsAdminの方がいい？(そもそもこいつら使うのか？)

2021-09-20 15:04 UTC, yuta-ike commented on app/server/src/domain/user/User.ts
> +  private assertHasIsAdmin(
HasIsAdminだからisAdminが設定済みか検査する意図だと思われー

2021-09-20 15:06 UTC, yuta-ike commented on app/server/src/domain/user/User.ts
> +  private assertHasIsAdmin(
> 上に合わせてisAdminの情報を持っているということを保証したけど、assertIsAdminの方がいい？(そもそもこいつら使うのか？)

そもそもisAdminがnullにならない、という設計にしたほうが見通し良さそう（現行のままならこのコードで問題ないと思います）

2021-09-20 15:09 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +  private assertHasIsAdmin(
roomIdがnull(をとりうるという前提でnull)だったり、指定がなければfalseというのでもいいのかもしれない。

roomIdがnullなのにadminかどうか判定できちゃうのがちょっと気持ち悪い気がしてnullにしてしまった

2021-09-20 15:14 UTC, yuta-ike commented on app/server/src/domain/user/User.ts
> +  private assertHasIsAdmin(
あ、わかります。未指定、isAdmin、notAdminの3状態取りたいって感じですよね。

ただ、そもそも未指定の状態が起こり得ない（roomIdもisAdminもコンストラクタで明示的に指定される & leaveRoomした時点でuserオブジェクトは捨てる）という方が見通し良さそうって感じです。

2021-09-20 15:19 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +  private assertHasIsAdmin(
そうだね、根本的に捨てちゃうのがいいかもしれない。

2021-09-20 15:25 UTC, TOMOFUMI-KONDO commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean | null,
あ、それなんですが、leaveRoomの中でフィールド変更する必要ないんじゃないかと思ったんですよね。フィールドnullにしてupdateしちゃうとroomにいた履歴が消し飛んでしまうので。
なのでleaveRoomの中ではassertメソッド実行するだけでいいのではないかと。updateもなしで。

どう思います？
@yuta-ike @Eri-0910

2021-09-20 15:29 UTC, yuta-ike commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean | null,
なるほど確かにassertionは必要か。良いと思われ。

ただそれとは別にuserインスタンスを破棄する処理が必要な気がするんだけど、一旦後回しで良いかな

2021-09-20 15:30 UTC, TOMOFUMI-KONDO commented on app/server/src/domain/user/User.ts
> +  private assertHasIsAdmin(
> isAdmin === trueのチェックも必要？

これは勘違いでした。忘れてください:pray:

2021-09-21 02:59 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean | null,
なるほど〜って思ったけど、null取らないならこれは一体何をassertしているのでしょう……？

2021-09-21 03:01 UTC, Eri-0910 commented on app/server/src/service/user/UserService.ts
>      this.userRepository.update(user)
DONE

2021-09-21 03:01 UTC, Eri-0910 commented on app/server/src/service/user/UserService.ts
>      this.userRepository.update(user)
DONE

2021-09-21 04:51 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean | null,
leaveRoomは削除しました。
_roomId, _iconId, _isAdminはnon-nullにしました。
結果いらなくなったassertを消しました。
assertを使っていた場所は(見つけられただけ)普通に値呼び出すのに修正しました。

2021-09-21 04:53 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +  private assertHasIsAdmin(
assertIsAdminの使い道が想定できなかったので一旦消しました。(使い道があるとすれば今もあるはずなのではとなった)(そんな難しいメソッドじゃないので必要になれば作ればよさそう？)

2021-09-21 04:56 UTC, Eri-0910 commented
全体を確認したときにapp.tsがなんか変だったのを修正して、コンフリクトも直しています。

2021-09-21 07:55 UTC, yuta-ike commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean,
めっちゃダイエットなされたww
ユーザーは振る舞いを持たないという感じでわかりやすくて良き。

```
public readonly roomId: string,
public readonly iconId: IconId,
public readonly isAdmin: boolean
```
でさらにダイエットできると思われます！（public & readonly = 誰でも読めるけど変更できない）

2021-09-21 07:55 UTC, yuta-ike commented on app/server/src/service/user/UserService.ts
>      this.roomRepository.update(room)
ユーザーのleaveの処理必要な気がするけど大丈夫ですかね...？
勘で言ってるけど`this.userRepository.delete`とか不要...？（速度優先で実装したいので特に致命的な問題が起こるものでなければスルーで大丈夫です）

2021-09-21 09:06 UTC, Eri-0910 commented on app/server/src/service/user/UserService.ts
>      this.roomRepository.update(room)
`this.userRepository.delete`は欲しい気はする。ただいままだ`userRepository`はまだメモリ上の配列で、次近藤さんのやつマージした時にまともなものできるはず……。とりあえず配列の該当箇所に`null`突っ込む感じで`userRepository.delete`作ればいいですかね？

2021-09-21 09:08 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean,
再ダイエット！

2021-09-21 09:16 UTC, Eri-0910 commented on app/server/src/service/user/UserService.ts
>      this.roomRepository.update(room)
だいぶ適当いってた。とりあえずかいてみました。
https://github.com/KoukiNAGATA/sushi-chat/pull/389/commits/c53ca8708fbbd8430cc8a5e9ef33d3da20afc195

2021-09-21 09:16 UTC, Eri-0910 commented on app/server/src/domain/user/User.ts
> +    private _isAdmin: boolean,
c078aec

2021-09-21 13:13 UTC, TOMOFUMI-KONDO approved these changes

2021-09-21 13:15 UTC, merged